### PR TITLE
docs: Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by iamrajiv**
Related:

https://github.com/keptn/community/pull/117
https://github.com/keptn/keptn/pull/7110
https://github.com/keptn/keptn.github.io/pull/1091

### CODE REVIEW

**Comment by iamrajiv** [comment]
@oleg-nenashev Please take a look.

**Review by oleg-nenashev — COMMENTED** [review]
I will start from migrating the Contributor Covenant 1.4 first, and then re-integrate this pull request so that we could vote on that in the community

**Comment by oleg-nenashev** [comment]
I will re-merge it later. Should we go after the latest version of the Code of Conduct while we are here?

**Comment by iamrajiv** [comment]
Yeah sure @oleg-nenashev.

**Comment by oleg-nenashev** [comment]
@iamrajiv so WDYT about updating to the new version of contributor covenant? Maybe a new pull request is easier

**Pull request closed without merging**
